# Generated by Django 4.0.5 on 2022-12-26 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVivienda', models.CharField(choices=[('1', 'Casa o departamento hasta primer piso'), ('2', 'Departamentos desde 2do piso en adelante'), ('3', 'Country/Barrio cerrado'), ('4', 'Vivienda de ocupación transitoria')], max_length=100)),
                ('materialesConstruccion', models.CharField(choices=[('1', 'Material'), ('2', 'Mat. Piedra y hasta 50% madera'), ('3', 'Madera'), ('4', 'Construcción en seco'), ('5', 'Adobe o similar')], max_length=100)),
                ('techo', models.CharField(choices=[('1', 'Material'), ('2', 'Material y tejas'), ('3', 'Tirantería de madera y tejas'), ('4', 'Tirantería de madera y zinc'), ('5', 'Zinc'), ('6', 'Tirantería de madera y paja'), ('7', 'Tirantería de madera y tejas de madera')], max_length=100)),
                ('cerramiento', models.CharField(choices=[('1', 'Totalmente cerrados'), ('2', 'Al menos un costado abierto'), ('3', 'Totalmente abiertos')], max_length=100)),
                ('CP', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('disyuntor', models.BooleanField()),
                ('alarma', models.BooleanField()),
                ('arlamaMonitoreo', models.BooleanField()),
                ('vigilancia', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
