from django import forms
from .models import CotizacionHogar

class CotizacionHogarForms(forms.ModelForm):

    class Meta:
        model=CotizacionHogar
        fields= ['tipoVivienda', 'materialesConstruccion', 'techo', 'cerramiento', 'CP', 'disyuntor', 'alarma', 'arlamaMonitoreo', 'vigilancia',
        'cob1_capital',
        'cob2_capital',
        'cob3_capital',
        'cob4_capital',
        'cob5_capital',
        'cob6_capital',
        'cob7_capital',
        'cob8_capital',
        'cob9_capital',
        'cob10_capital',
        'cob11_capital',
        'cob12_capital',
        'cob13_capital',
        'cob14_capital',
        'cob15_capital',
        'cob16_capital',
        'cob17_capital',
        'cob18_capital',
        'cob19_capital',
        'cob20_capital',
        ]

        labels = {
            'cob1_capital':'Incendio edificio a primer riesgo absoluto',
            'cob2_capital':'Incendio contenido a primer riesgo absoluto',
            'cob3_capital':'Robo y/o hurto del contenido general',
            'cob4_capital':'Gastos de limpieza, retiro de escrombros, demolición del edificio',
            'cob5_capital':'Gastos de limpieza, retiro del mobiliario',
            'cob6_capital':'HCVT (Huracán, Vendaval, Ciclón, Tornado)',
            'cob7_capital':'Granizo',
            'cob8_capital':'Gastos de alojamiento',
            'cob9_capital':'Responsabilidad Civil por incendio o explosión',
            'cob10_capital':'Bauleras y dependencias anexas',
            'cob11_capital':'Objetos especificos: Todo riesgo en domicilio',
            'cob12_capital':'Electrónicos',
            'cob13_capital':'Electrodomésticos - Aparatos o equipos electrónicos de uso doméstico',
            'cob14_capital':'Accidentes personales',
            'cob15_capital':'Cristales',
            'cob16_capital':'Responsabilidad civil hechos privados',
            'cob17_capital':'Daños por agua',
            'cob18_capital':'Pérdidas de alimentos en freezer',
            'cob19_capital':'Palos de golf',
            'cob20_capital':'Daños estéticos',
        }

        widgets = {
            'tipoVivienda': forms.Select(attrs={'class': 'form-control'}),
            'materialesConstruccion': forms.Select(attrs={'class': 'form-control'}),
            'techo': forms.Select(attrs={'class': 'form-control'}),
            'cerramiento': forms.Select(attrs={'class': 'form-control'}),
            'CP': forms.NumberInput(attrs={'class': 'form-control'}),
            'disyuntor': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'alarma': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'arlamaMonitoreo': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'vigilancia': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'cob1_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0', 'onchange': 'myFunction()'}),
            'cob2_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob3_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob4_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob5_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob6_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob7_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob8_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob9_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob10_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob11_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob12_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob13_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob14_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob15_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob16_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob17_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob18_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob19_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
            'cob20_capital': forms.NumberInput(attrs={'class': 'form-control form-control-sm', 'max': '1000000', 'value': '0'}),
        }